<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>10</LangVersion>
        <AssemblyName>OmsiTools.Common</AssemblyName>
        <RootNamespace>OmsiTools.Common</RootNamespace>
        <PackageId>OmsiTools.Common</PackageId>
        <Authors>OmsiTools.Common</Authors>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <None Update="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Squid-Box.SevenZipSharp" Version="1.6.2.24" />
    </ItemGroup>

</Project>
